### ISSUE TITLE
ImageExample doesn't work anymore

### ISSUE THREAD

**Issue by josephtaylor** [josephtaylor/ColorScheme#9]
The image URL referenced in the example doesn't exist anymore

**Comment by vhlnd** [comment]
Hi i would like to work on this issue, should i put a random image or is there a specific image im suppose to put?

**Comment by josephtaylor** [comment]
Any image you want, as long as it's hosted in a location that's unlikely to go away.

**Comment by vhlnd** [comment]
awesome will update it.

**Comment by josephtaylor** [comment]
Thanks!
